name: Node.js Package

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm ci
      - run: npm run lint
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
      - run: npm publish
        env:
          NPM_AUTH_TOKEN: ${{secrets.npm_token}}
